"""
Provider-agnostic VCS write guards.

The canonical home for guards that apply to *any* git host (GitLab, GitHub,
BitBucket): no-AI-attribution, the MR/PR title protocol, protected-ref, and the
per-provider write-enable env gate. Both `modules/vcs/providers/*` call these
directly; `modules/gitlab/guards.py` re-exports the generic ones so the existing
`GitLabClient` and its tests keep importing them unchanged.

Depends only on `shared.config` and `os` — it imports nothing from
`modules.gitlab.*` or `modules.vcs.providers.*`, so there is no import cycle.
Pure Python / env: identical behaviour on Windows and macOS.
"""

from __future__ import annotations

import os

from shared.config import PROTECTED_REFS, PROTECTED_REF_PREFIXES

_TRUTHY = {"1", "true", "yes", "on"}


class GuardError(Exception):
    """Base class for VCS guard violations."""


class ProtectedRefError(GuardError):
    pass


class AgentAttributionForbiddenError(GuardError):
    pass


class MrTitleProtocolError(GuardError):
    pass


class VcsWriteDisabledError(GuardError):
    """Raised when a provider's write env gate is off."""


def _is_protected_ref(ref: str) -> bool:
    return ref in PROTECTED_REFS or ref.startswith(PROTECTED_REF_PREFIXES)


def assert_not_protected_ref(ref: str) -> None:
    """Block operations that write to prod branches: push, trigger_pipeline."""
    if _is_protected_ref(ref):
        raise ProtectedRefError(
            f"Ref '{ref}' is protected — pushes and pipeline triggers are forbidden"
        )


def assert_no_agent_attribution(text: str) -> None:
    """Forbid public MR/PR text that says the action was done by Claude/AI.

    Applies to any provider: titles, descriptions and comments are written under
    the user's account and must not mention the assistant.
    """
    if not text:
        return
    lowered = text.lower()
    forbidden = ("claude", "клод", "ai assistant", "ии-ассистент", "generated by ai")
    if any(token in lowered for token in forbidden):
        raise AgentAttributionForbiddenError(
            "MR/PR titles, descriptions and comments must not mention Claude/AI; "
            "actions are performed under the user's account"
        )


def assert_mr_title_is_source_branch(title: str, source_branch: str) -> None:
    """Enforce the MR/PR title protocol: the title is the source branch name."""
    if title != source_branch:
        raise MrTitleProtocolError(
            f"MR/PR title must equal the source branch name literally "
            f"(title={title!r}, source_branch={source_branch!r})"
        )


def is_write_enabled(provider: str, default: bool = False) -> bool:
    """Read ``<PROVIDER>_WRITE_ENABLED`` from env at call time.

    ``default`` is used when the var is unset (GitHub/BitBucket default off).
    """
    raw = os.getenv(f"{provider.upper()}_WRITE_ENABLED")
    if raw is None:
        return default
    return raw.strip().lower() in _TRUTHY


def assert_write_enabled(provider: str, default: bool = False) -> None:
    if not is_write_enabled(provider, default=default):
        env_var = f"{provider.upper()}_WRITE_ENABLED"
        raise VcsWriteDisabledError(
            f"{provider} write operations are disabled. Set {env_var}=true in "
            f"config/{provider}/.env and request the write action explicitly in the "
            f"current chat."
        )
