"""Jira write guards — text validation before any Jira/Confluence HTTP write."""


class JiraGuardError(Exception):
    pass


class AgentAttributionForbiddenError(JiraGuardError):
    pass


class JiraWriteTextError(JiraGuardError):
    pass


def assert_no_agent_attribution(text: str) -> None:
    """Forbid Jira/Confluence text that names Claude/AI as author."""
    if not text:
        return
    lowered = text.lower()
    forbidden = ("claude", "клод", "ai assistant", "ии-ассистент", "generated by ai")
    if any(token in lowered for token in forbidden):
        raise AgentAttributionForbiddenError(
            "Jira/Confluence text must not mention Claude/AI; "
            "actions are performed under the user's account"
        )


def assert_valid_jira_write_text(text: str, max_chars: int = 10_000) -> None:
    """Validate user-visible Jira write text before any HTTP write request."""
    if text is None or not str(text).strip():
        raise JiraWriteTextError("Jira write text must not be empty")
    if len(text) > max_chars:
        raise JiraWriteTextError(
            f"Jira write text is too long ({len(text)} chars); max is {max_chars}"
        )
    try:
        assert_no_agent_attribution(text)
    except AgentAttributionForbiddenError as exc:
        raise JiraWriteTextError(
            "Jira comments/descriptions must not mention Claude/AI; "
            "actions are performed under the user's account"
        ) from exc
